parameters:
    user_full_name: "user one"
    links:
        - "https://github.com/imflash217/portfolio"
        - "https://github.com/sutr-am/vedika"
        - "https://github.com/imflash217/TensorTonic-Solutions"
