services:
    mongodb:
        image: mongo:latest
        container_name: vedika_mongo
        restart: always
        ports:
            - "27017:27017"
        environment:
            # Map the reserved MongoDB keys to your custom .env variables
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
