@startuml
skinparam dpi 600

class CleaningService {
}


class BaseRawDomain {
    + id : UUID
    + title : str
    + content : str
    + platform : str
    + source_url : HttpUrl
    + user_id : UUID
    + category : DataCategory
    + state : DataState
    + data : Any
}


class BaseCleanedDomain {
    + id : UUID
    + title : str
    + content : str
    + platform : str
    + source_url : HttpUrl
    + user_id : UUID
    + category : DataCategory
    + state : DataState
    + data : Any
}


class CodebaseRawDomain {
    + id : UUID
    + title : str
    + content : str
    + platform : str
    + source_url : HttpUrl
    + user_id : UUID
    + category : DataCategory
    + state : DataState
    + data : Any
}

@enduml