@startuml packages_Targeted
set namespaceSeparator none
package "vedika.application.services.cleaning_service" as vedika.application.services.cleaning_service {
}
package "vedika.domain.cleaned" as vedika.domain.cleaned {
}
package "vedika.domain.raw" as vedika.domain.raw {
}
vedika.application.services.cleaning_service --> vedika.domain.cleaned
vedika.application.services.cleaning_service --> vedika.domain.raw
@enduml
