github_token: ${oc.env:GITHUB_TOKEN}

connections:
    primary_mongo:
        driver: mongo
        host: mongodb://${oc.env:MONGO_USER}:${oc.env:MONGO_PASSWORD}@${oc.env:MONGO_HOST_IP}:${oc.env:MONGO_PORT}
        db_name: ${oc.env:MONGO_DB_NAME_PRIMARY}
    secondary_mongo:
        driver: mongo
        host: mongodb://${oc.env:MONGO_USER}:${oc.env:MONGO_PASSWORD}@${oc.env:MONGO_HOST_IP}:${oc.env:MONGO_PORT}
        db_name: ${oc.env:MONGO_DB_NAME_SECONDARY}

storage_routes:
    users:
        connection: primary_mongo
        target: users
    categories:
        codebases:
            raw:
                connection: primary_mongo
                target: codebases_raw
            cleaned:
                connection: secondary_mongo
                target: codebases_cleaned
