connections:
    primary_mongo:
        driver: mongo
        host: mongodb://${oc.env:MONGO_USER}:${oc.env:MONGO_PASSWORD}@${oc.env:MONGO_HOST_IP}:${oc.env:MONGO_PORT}
        db_name: ${oc.env:MONGO_DB_NAME}

storage_routes:
    users:
        connection: primary_mongo
        target: users
    categories:
        codebases:
            raw:
                connection: primary_mongo
                target: codebases_raw
            cleaned:
                connection: primary_mongo
                target: codebases_cleaned
