import re
import sys


def main():
    # Regular expression to match standard ANSI escape codes (colors, styles, cursor jumps)
    ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')

    for line in sys.stdin:
        # 1. Stream raw, untouched lines directly to the terminal (keeping colors and live progress bars)
        sys.stdout.write(line)
        sys.stdout.flush()

        # 2. If a log file path was passed, clean it up for file storage
        if len(sys.argv) > 1:
            log_file_path = sys.argv[1]

            # Strip ANSI colors and styles
            clean_line = ansi_escape.sub('', line)

            # Handle carriage returns (\r) typically generated by progress bars (tqdm)
            # If a line uses \r to overwrite itself, keep only the final updated segment or strip them
            if '\r' in clean_line:
                # Split by \r and take the last active segment so logs don't double-print
                clean_line = clean_line.split('\r')[-1]

            with open(log_file_path, 'a', encoding='utf-8') as f:
                f.write(clean_line)

if __name__ == "__main__":
    main()
