@startmindmap
* root node

** some first level node
***_ second level node
***_ another second level node
***_ foo
***_ bar
***_ foobar

** another first level node
***_ second level node
***_ another second level node
***_ foo
***_ bar
***_ foobar
***_ second level node
***_ another second level node
***_ foo
***_ bar
***_ foobar


** another first level node
***_ second level node
***_ another second level node
***_ foo
***_ bar
***_ foobar
***_ second level node
***_ another second level node
***_ foo
****_ foobar
****_ foobar
****_ foobar
****_ foobar
****_ foobarnbnbnbnbnbnbnjbkbkbkj ❤️
****_ foobar
****_ foobar
****_ foobar
****_ foobar
****_ foobar
****_ foobar
****_ foobar

***_ bar
***_ foobar
****_ foobar
****_ foobar
****_ foobar
****_ foobar
****_ foobar
****_ foobar
****_ foobar
****_ foobar
****_ foobar








caption figure 1
title My super title
*_ <&flag>Debian
**_ <&globe>Ubuntu
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
** <&graph>LMDE
** <&pulse>SolydXK
** <&people>SteamOS
** <&star>Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
header
My super header
endheader
center footer My super footer
legend right
Short
legend
endlegend

@endmindmap